const mongoose = require("mongoose");
const Caregiver = require("./src/models/Caregiver");
require("dotenv").config();

const verificationDetails = {
  aadhaar: { url: "https://res.cloudinary.com/dvk6auu6m/image/upload/v1/docs/aadhaar.pdf", verified: true },
  policeClearance: { url: "https://res.cloudinary.com/dvk6auu6m/image/upload/v1/docs/police.pdf", verified: true },
  nursingCertificate: { url: "https://res.cloudinary.com/dvk6auu6m/image/upload/v1/docs/certificate.pdf", verified: true },
};

const caregivers = [
  {
    userId: null,
    name: "Dr. Arjun Mehta",
    image: "/images/caregivers/1.png",
    phone: "9876543210",
    city: "Delhi",
    experience: 20,
    specializations: ["nursing", "elderly_care"],
    languages: ["Hindi", "English"],
    hourlyRate: 150,
    dailyRate: 1000,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.8,
    totalReviews: 45,
    email: "liam.smith@gmail.com",
    bio: "Experienced caregiver specializing in elderly care and patient support with a compassionate approach.",
    qualifications: [{ degree: "B.Sc Nursing", institution: "AIIMS Delhi", year: 2017 }],
    certifications: ["Geriatric Care Certified", "CPR & First Aid"],
    workHistory: [{
      organization: "Apollo Hospital Delhi", position: "Senior Nurse",
      duration: "3 years", startDate: new Date("2019-01-01"), endDate: new Date("2022-01-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: false, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["South Delhi", "Central Delhi", "Dwarka"],
    ratingBreakdown: { fiveStar: 30, fourStar: 10, threeStar: 3, twoStar: 1, oneStar: 1 },
    performanceMetrics: { successRate: 96, averageResponseTime: "1 hour", casesCompleted: 80, repeatBookings: 25 },
    status: "available",
    topRated: true,
  },
  {
    userId: null,
    name: "Dr. Priya Sharma",
    image: "/images/caregivers/2.png",
    phone: "9876543211",
    city: "Delhi",
    experience: 3,
    specializations: ["physiotherapy"],
    languages: ["Hindi", "English"],
    hourlyRate: 200,
    dailyRate: 1400,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.5,
    totalReviews: 30,
    email: "sophia.williams@gmail.com",
    bio: "Dedicated physiotherapist with 3 years of experience in rehabilitation and mobility improvement for all age groups.",
    qualifications: [{ degree: "BPT (Bachelor of Physiotherapy)", institution: "Delhi University", year: 2020 }],
    certifications: ["Certified Physiotherapist", "CPR Certified"],
    workHistory: [{
      organization: "Max Hospital Delhi", position: "Physiotherapist",
      duration: "2 years", startDate: new Date("2020-06-01"), endDate: new Date("2022-06-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: false,
    serviceAreas: ["North Delhi", "West Delhi", "Rohini"],
    ratingBreakdown: { fiveStar: 18, fourStar: 8, threeStar: 3, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 92, averageResponseTime: "2 hours", casesCompleted: 45, repeatBookings: 15 },
    status: "available",
    topRated: false,
  },
  {
    userId: null,
    name: "Dr. Ananya Singh",
    image: "/images/caregivers/3.png",
    phone: "9876543212",
    city: "Delhi",
    experience: 7,
    specializations: ["nursing", "post_hospital"],
    languages: ["Hindi", "Gujarati"],
    hourlyRate: 180,
    dailyRate: 1200,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.9,
    totalReviews: 67,
    email: "emma.johnson@gmail.com",
    bio: "Highly skilled nurse with 7 years of experience in post-hospital care, wound management, and nursing support for recovering patients.",
    qualifications: [{ degree: "B.Sc Nursing", institution: "Ahmedabad Nursing College", year: 2015 }],
    certifications: ["Wound Care Specialist", "Advanced CPR"],
    workHistory: [{
      organization: "Fortis Hospital Delhi", position: "Head Nurse",
      duration: "4 years", startDate: new Date("2017-03-01"), endDate: new Date("2021-03-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["East Delhi", "Noida", "Greater Noida"],
    ratingBreakdown: { fiveStar: 55, fourStar: 8, threeStar: 2, twoStar: 1, oneStar: 1 },
    performanceMetrics: { successRate: 98, averageResponseTime: "45 minutes", casesCompleted: 120, repeatBookings: 50 },
    status: "available",
    topRated: true,
  },
  {
    userId: null,
    name: "Dr. Kavya Nair",
    image: "/images/caregivers/4.png",
    phone: "9876543213",
    city: "Delhi",
    experience: 4,
    specializations: ["elderly_care", "post_hospital"],
    languages: ["Hindi", "Punjabi"],
    hourlyRate: 160,
    dailyRate: 1100,
    available: false,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.3,
    totalReviews: 22,
    email: "olivia.brown@gmail.com",
    bio: "Caring and patient caregiver with 4 years of experience supporting elderly individuals and post-hospital patients in their daily needs.",
    qualifications: [{ degree: "Diploma in Nursing", institution: "Punjab Nursing Institute", year: 2018 }],
    certifications: ["Elder Care Certified", "First Aid Certified"],
    workHistory: [{
      organization: "HelpAge India - Delhi", position: "Care Assistant",
      duration: "3 years", startDate: new Date("2018-07-01"), endDate: new Date("2021-07-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: false, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: false,
    serviceAreas: ["West Delhi", "Punjabi Bagh", "Janakpuri"],
    ratingBreakdown: { fiveStar: 10, fourStar: 8, threeStar: 3, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 88, averageResponseTime: "3 hours", casesCompleted: 35, repeatBookings: 10 },
    status: "available",
    topRated: false,
  },
  {
    userId: null,
    name: "Dr. Rohan Mehta",
    image: "/images/caregivers/5.png",
    phone: "9876543214",
    city: "Delhi",
    experience: 30,
    specializations: ["nursing"],
    languages: ["Hindi", "Tamil", "English"],
    hourlyRate: 170,
    dailyRate: 1150,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.7,
    totalReviews: 38,
    email: "noah.anderson@gmail.com",
    bio: "Experienced nurse fluent in Hindi, Tamil, and English, providing quality home nursing services across Delhi for 6 years.",
    qualifications: [{ degree: "B.Sc Nursing", institution: "Sri Ramachandra University Chennai", year: 2016 }],
    certifications: ["Critical Care Nursing", "CPR Certified"],
    workHistory: [{
      organization: "AIIMS Delhi", position: "Staff Nurse",
      duration: "3 years", startDate: new Date("2018-01-01"), endDate: new Date("2021-01-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: false, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: true, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["South Delhi", "Saket", "Vasant Kunj"],
    ratingBreakdown: { fiveStar: 25, fourStar: 10, threeStar: 2, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 94, averageResponseTime: "1.5 hours", casesCompleted: 65, repeatBookings: 20 },
    status: "available",
    topRated: true,
  },
  {
    userId: null,
    name: "Dr. Riya Mehta",
    image: "/images/caregivers/6.png",
    phone: "9876543215",
    city: "Mumbai",
    experience: 2,
    specializations: ["nursing", "elderly_care"],
    languages: ["Hindi", "Malayalam", "English"],
    hourlyRate: 200,
    dailyRate: 1400,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.9,
    totalReviews: 89,
    email: "ava.martinez@gmail.com",
    bio: "Top-rated caregiver in Mumbai with 8 years of experience in nursing and elderly care. Known for patience, professionalism, and multilingual communication.",
    qualifications: [{ degree: "M.Sc Nursing", institution: "KEM Hospital Mumbai", year: 2014 }],
    certifications: ["Palliative Care Certified", "Geriatric Nursing", "Advanced CPR"],
    workHistory: [{
      organization: "Tata Memorial Hospital Mumbai", position: "Senior Nurse",
      duration: "5 years", startDate: new Date("2015-01-01"), endDate: new Date("2020-01-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["Andheri", "Bandra", "Juhu", "Santacruz"],
    ratingBreakdown: { fiveStar: 72, fourStar: 12, threeStar: 3, twoStar: 1, oneStar: 1 },
    performanceMetrics: { successRate: 99, averageResponseTime: "30 minutes", casesCompleted: 160, repeatBookings: 70 },
    status: "available",
    topRated: true,
  },
  {
    userId: null,
    name: "Dr. Karan Malhotra",
    image: "/images/caregivers/7.png",
    phone: "9876543216",
    city: "Mumbai",
    experience: 20,
    specializations: ["physiotherapy"],
    languages: ["Hindi", "Marathi", "English"],
    hourlyRate: 220,
    dailyRate: 1500,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.4,
    totalReviews: 18,
    email: "ethan.clark@gmail.com",
    bio: "Young and energetic physiotherapist with expertise in sports injury rehabilitation and post-operative care in Mumbai.",
    qualifications: [{ degree: "BPT", institution: "Smt. Kashibai Navale College of Physiotherapy Pune", year: 2022 }],
    certifications: ["Sports Physiotherapy Certification", "CPR Certified"],
    workHistory: [{
      organization: "Kokilaben Dhirubhai Ambani Hospital Mumbai", position: "Junior Physiotherapist",
      duration: "1.5 years", startDate: new Date("2022-07-01"), endDate: new Date("2024-01-01"),
    }],
    workingShifts: {
      morning: { available: false, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: false,
    serviceAreas: ["Thane", "Mulund", "Ghatkopar"],
    ratingBreakdown: { fiveStar: 10, fourStar: 5, threeStar: 2, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 85, averageResponseTime: "2.5 hours", casesCompleted: 25, repeatBookings: 8 },
    status: "available",
    topRated: false,
  },
  {
    userId: null,
    name: "Dr. Aditya Verma",
    image: "/images/caregivers/8.png",
    phone: "9876543217",
    city: "Mumbai",
    experience: 17,
    specializations: ["post_hospital", "nursing"],
    languages: ["Hindi", "English"],
    hourlyRate: 190,
    dailyRate: 1300,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.6,
    totalReviews: 41,
    email: "james.walker@gmail.com",
    bio: "Experienced male nurse with 5 years in post-hospital and home nursing, ensuring smooth recovery and patient comfort in Mumbai.",
    qualifications: [{ degree: "B.Sc Nursing", institution: "MGM Medical College Mumbai", year: 2017 }],
    certifications: ["Post-Surgical Care Certified", "Advanced First Aid"],
    workHistory: [{
      organization: "Hinduja Hospital Mumbai", position: "Staff Nurse",
      duration: "3 years", startDate: new Date("2019-04-01"), endDate: new Date("2022-04-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: false, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: true, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["Dadar", "Parel", "Matunga", "Sion"],
    ratingBreakdown: { fiveStar: 26, fourStar: 10, threeStar: 3, twoStar: 1, oneStar: 1 },
    performanceMetrics: { successRate: 93, averageResponseTime: "1 hour", casesCompleted: 70, repeatBookings: 22 },
    status: "available",
    topRated: false,
  },
  {
    userId: null,
    name: "Dr. Aakanksha Patel",
    image: "/images/caregivers/9.png",
    phone: "9876543218",
    city: "Mumbai",
    experience: 7,
    specializations: ["elderly_care"],
    languages: ["Hindi", "Marathi"],
    hourlyRate: 175,
    dailyRate: 1200,
    available: false,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.8,
    totalReviews: 112,
    email: "isabella.anderson@gmail.com",
    bio: "One of Mumbai's most experienced elderly care specialists with a decade of hands-on experience, trusted by over 100 families.",
    qualifications: [{ degree: "Diploma in Geriatric Care", institution: "Bombay Nursing College", year: 2012 }],
    certifications: ["Dementia Care Specialist", "Geriatric Care Certified", "CPR Certified"],
    workHistory: [{
      organization: "Hinduja Healthcare Mumbai", position: "Elderly Care Coordinator",
      duration: "5 years", startDate: new Date("2014-01-01"), endDate: new Date("2019-01-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: false, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: false,
    serviceAreas: ["Borivali", "Kandivali", "Malad", "Goregaon"],
    ratingBreakdown: { fiveStar: 90, fourStar: 15, threeStar: 5, twoStar: 1, oneStar: 1 },
    performanceMetrics: { successRate: 97, averageResponseTime: "2 hours", casesCompleted: 200, repeatBookings: 90 },
    status: "available",
    topRated: true,
  },
  {
    userId: null,
    name: "Dr. Suresh Reddy",
    image: "/images/caregivers/10.png",
    phone: "9876543219",
    city: "Bangalore",
    experience: 4,
    specializations: ["nursing", "physiotherapy"],
    languages: ["Hindi", "Kannada", "English"],
    hourlyRate: 160,
    dailyRate: 1100,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.5,
    totalReviews: 29,
    email: "benjamin.hall@gmail.com",
    bio: "Versatile healthcare professional offering both nursing and physiotherapy services in Bangalore with 4 years of dual expertise.",
    qualifications: [
      { degree: "B.Sc Nursing", institution: "Rajiv Gandhi University Bangalore", year: 2018 },
      { degree: "BPT", institution: "Manipal College of Health Professions", year: 2019 },
    ],
    certifications: ["Certified Physiotherapist", "Nursing Council Registered"],
    workHistory: [{
      organization: "Manipal Hospital Bangalore", position: "Staff Nurse cum Physiotherapy Assistant",
      duration: "3 years", startDate: new Date("2019-09-01"), endDate: new Date("2022-09-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: false, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: false,
    serviceAreas: ["Indiranagar", "Koramangala", "HSR Layout"],
    ratingBreakdown: { fiveStar: 17, fourStar: 8, threeStar: 3, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 90, averageResponseTime: "2 hours", casesCompleted: 48, repeatBookings: 14 },
    status: "available",
    topRated: false,
  },
  {
    userId: null,
    name: "Dr. Rajesh Kumar",
    image: "/images/caregivers/11.png",
    phone: "9876543220",
    city: "Bangalore",
    experience: 26,
    specializations: ["elderly_care", "post_hospital"],
    languages: ["Kannada", "English"],
    hourlyRate: 155,
    dailyRate: 1050,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.7,
    totalReviews: 54,
    email: "lucas.allen@gmail.com",
    bio: "Experienced Bangalore-based caregiver with 6 years of expertise in elderly support and post-hospital home care services.",
    qualifications: [{ degree: "Diploma in Home Health Aide", institution: "St. John's Medical College Bangalore", year: 2016 }],
    certifications: ["Post-Hospital Care Certified", "First Aid & CPR"],
    workHistory: [{
      organization: "Apollo Hospital Bangalore", position: "Home Care Specialist",
      duration: "4 years", startDate: new Date("2017-06-01"), endDate: new Date("2021-06-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["Whitefield", "Marathahalli", "Bellandur"],
    ratingBreakdown: { fiveStar: 38, fourStar: 12, threeStar: 3, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 95, averageResponseTime: "1.5 hours", casesCompleted: 95, repeatBookings: 35 },
    status: "available",
    topRated: true,
  },
  {
    userId: null,
    name: "Dr. Sanjeev Kumar",
    image: "/images/caregivers/12.png",
    phone: "9876543221",
    city: "Bangalore",
    experience: 21,
    specializations: ["nursing"],
    languages: ["Malayalam", "Kannada", "English"],
    hourlyRate: 185,
    dailyRate: 1250,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.9,
    totalReviews: 76,
    email: "henry.young@gmail.com",
    bio: "Highly qualified and trusted home nurse with 9 years of experience, fluent in Malayalam, Kannada, and English, serving patients across Bangalore.",
    qualifications: [{ degree: "M.Sc Nursing", institution: "NIMHANS Bangalore", year: 2013 }],
    certifications: ["Critical Care Nursing", "Ventilator Management", "Advanced CPR"],
    workHistory: [{
      organization: "Narayana Health Bangalore", position: "Senior Nurse - ICU",
      duration: "5 years", startDate: new Date("2014-02-01"), endDate: new Date("2019-02-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: false, timeRange: "6 PM - 12 AM" },
      night: { available: true, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["Jayanagar", "JP Nagar", "Banashankari", "Kanakapura Road"],
    ratingBreakdown: { fiveStar: 62, fourStar: 10, threeStar: 2, twoStar: 1, oneStar: 1 },
    performanceMetrics: { successRate: 98, averageResponseTime: "45 minutes", casesCompleted: 140, repeatBookings: 60 },
    status: "available",
    topRated: true,
  },
  {
    userId: null,
    name: "Dr. Sunali Sharma",
    image: "/images/caregivers/13.png",
    phone: "9876543222",
    city: "Kolkata",
    experience: 15,
    specializations: ["nursing", "elderly_care"],
    languages: ["Bengali", "Hindi", "English"],
    hourlyRate: 140,
    dailyRate: 950,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.4,
    totalReviews: 21,
    email: "mia.thompson@gmail.com",
    bio: "Caring and dedicated nurse with 3 years of experience providing nursing and elderly care services across Kolkata with a warm, family-like approach.",
    qualifications: [{ degree: "B.Sc Nursing", institution: "Medical College Kolkata", year: 2021 }],
    certifications: ["Nursing Council Registered", "First Aid Certified"],
    workHistory: [{
      organization: "SSKM Hospital Kolkata", position: "Junior Nurse",
      duration: "2 years", startDate: new Date("2021-07-01"), endDate: new Date("2023-07-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: false, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: false,
    serviceAreas: ["Salt Lake", "New Town", "Dum Dum"],
    ratingBreakdown: { fiveStar: 12, fourStar: 6, threeStar: 2, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 87, averageResponseTime: "2 hours", casesCompleted: 30, repeatBookings: 9 },
    status: "available",
    topRated: false,
  },
  {
    userId: null,
    name: "Dr. Daniel Roy",
    image: "/images/caregivers/14.png",
    phone: "9876543223",
    city: "Kolkata",
    experience: 5,
    specializations: ["physiotherapy"],
    languages: ["Bengali", "Hindi"],
    hourlyRate: 150,
    dailyRate: 1000,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.6,
    totalReviews: 33,
    email: "daniel.scott@gmail.com",
    bio: "Skilled physiotherapist with 5 years of experience delivering in-home therapy sessions tailored to each patient's needs in Kolkata.",
    qualifications: [{ degree: "BPT", institution: "Calcutta Medical College", year: 2018 }],
    certifications: ["Neurological Physiotherapy", "CPR Certified"],
    workHistory: [{
      organization: "Belle Vue Clinic Kolkata", position: "Physiotherapist",
      duration: "3 years", startDate: new Date("2018-10-01"), endDate: new Date("2021-10-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: false,
    serviceAreas: ["Ballygunge", "Alipore", "Park Street"],
    ratingBreakdown: { fiveStar: 21, fourStar: 8, threeStar: 3, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 92, averageResponseTime: "2 hours", casesCompleted: 58, repeatBookings: 18 },
    status: "available",
    topRated: false,
  },
  {
    userId: null,
    name: "Dr. Sanjay Kumar",
    image: "/images/caregivers/15.png",
    phone: "9876543224",
    city: "Hyderabad",
    experience: 7,
    specializations: ["nursing", "post_hospital"],
    languages: ["Urdu", "Hindi", "Telugu", "English"],
    hourlyRate: 165,
    dailyRate: 1100,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.8,
    totalReviews: 61,
    email: "charlotte.taylor@gmail.com",
    bio: "Highly experienced nurse fluent in 4 languages, providing exceptional nursing and post-hospital care with cultural sensitivity in Hyderabad.",
    qualifications: [{ degree: "B.Sc Nursing", institution: "Osmania Medical College Hyderabad", year: 2015 }],
    certifications: ["Advanced Nursing Care", "Post-Surgical Care Certified", "CPR"],
    workHistory: [{
      organization: "KIMS Hospital Hyderabad", position: "Senior Staff Nurse",
      duration: "4 years", startDate: new Date("2016-01-01"), endDate: new Date("2020-01-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["Banjara Hills", "Jubilee Hills", "Madhapur", "Gachibowli"],
    ratingBreakdown: { fiveStar: 47, fourStar: 10, threeStar: 3, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 96, averageResponseTime: "1 hour", casesCompleted: 105, repeatBookings: 42 },
    status: "available",
    topRated: true,
  },
  {
    userId: null,
    name: "Dr. Pratibha Singh",
    image: "/images/caregivers/16.png",
    phone: "9876543225",
    city: "Hyderabad",
    experience: 10,
    specializations: ["elderly_care"],
    languages: ["Telugu", "Hindi", "English"],
    hourlyRate: 155,
    dailyRate: 1050,
    available: false,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.3,
    totalReviews: 17,
    email: "matthew.green@gmail.com",
    bio: "Dedicated caregiver with 4 years of experience in elderly support, assisting with daily activities and providing companionship for seniors in Hyderabad.",
    qualifications: [{ degree: "Diploma in Care of the Elderly", institution: "Hyderabad Skill Development Centre", year: 2019 }],
    certifications: ["Elder Care Certified", "First Aid Certified"],
    workHistory: [{
      organization: "Sunshine Old Age Home Hyderabad", position: "Senior Care Attendant",
      duration: "3 years", startDate: new Date("2019-06-01"), endDate: new Date("2022-06-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: false, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: false,
    serviceAreas: ["Secunderabad", "Begumpet", "Ameerpet"],
    ratingBreakdown: { fiveStar: 8, fourStar: 6, threeStar: 2, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 85, averageResponseTime: "3 hours", casesCompleted: 28, repeatBookings: 7 },
    status: "available",
    topRated: false,
  },
  {
    userId: null,
    name: "Dr. Sonakshi Rao",
    image: "/images/caregivers/17.png",
    phone: "9876543226",
    city: "Hyderabad",
    experience: 6,
    specializations: ["physiotherapy", "post_hospital"],
    languages: ["Malayalam", "Telugu", "English"],
    hourlyRate: 195,
    dailyRate: 1350,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.7,
    totalReviews: 48,
    email: "amelia.davis@gmail.com",
    bio: "Skilled physiotherapist and post-hospital care specialist with 6 years of experience helping patients regain strength and independence in Hyderabad.",
    qualifications: [{ degree: "MPT (Master of Physiotherapy)", institution: "Manipal University", year: 2017 }],
    certifications: ["Orthopedic Physiotherapy", "Pulmonary Rehab Certified", "CPR"],
    workHistory: [{
      organization: "Yashoda Hospitals Hyderabad", position: "Senior Physiotherapist",
      duration: "4 years", startDate: new Date("2018-03-01"), endDate: new Date("2022-03-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["Kukatpally", "HITEC City", "Kondapur", "Miyapur"],
    ratingBreakdown: { fiveStar: 34, fourStar: 10, threeStar: 3, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 94, averageResponseTime: "1.5 hours", casesCompleted: 85, repeatBookings: 30 },
    status: "available",
    topRated: true,
  },
  {
    userId: null,
    name: "Dr. Mukesh Kumar",
    image: "/images/caregivers/18.png",
    phone: "9876543227",
    city: "Chennai",
    experience: 14,
    specializations: ["nursing", "elderly_care"],
    languages: ["Tamil", "English"],
    hourlyRate: 170,
    dailyRate: 1150,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.6,
    totalReviews: 57,
    email: "alexander.king@gmail.com",
    bio: "Experienced and trusted home nurse with 8 years of expertise in nursing and elderly care, well-versed in Tamil healthcare culture and practices.",
    qualifications: [{ degree: "B.Sc Nursing", institution: "Sri Ramachandra Institute Chennai", year: 2014 }],
    certifications: ["Geriatric Care Certified", "Diabetes Care Specialist", "CPR"],
    workHistory: [{
      organization: "Apollo Hospital Chennai", position: "Staff Nurse",
      duration: "5 years", startDate: new Date("2015-06-01"), endDate: new Date("2020-06-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: false, timeRange: "6 PM - 12 AM" },
      night: { available: true, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: true,
    serviceAreas: ["Anna Nagar", "T. Nagar", "Adyar", "Mylapore"],
    ratingBreakdown: { fiveStar: 40, fourStar: 12, threeStar: 3, twoStar: 1, oneStar: 1 },
    performanceMetrics: { successRate: 93, averageResponseTime: "1 hour", casesCompleted: 100, repeatBookings: 38 },
    status: "available",
    topRated: false,
  },
  {
    userId: null,
    name: "Dr. Shabnam Patel",
    image: "/images/caregivers/19.png",
    phone: "9876543228",
    city: "Chennai",
    experience: 15,
    specializations: ["post_hospital"],
    languages: ["Tamil", "Hindi", "English"],
    hourlyRate: 160,
    dailyRate: 1100,
    available: true,
    verified: true,
    verificationStatus: "active",
    verificationDetails,
    rating: 4.5,
    totalReviews: 36,
    email: "harper.wilson@gmail.com",
    bio: "Dedicated post-hospital care specialist with 5 years of experience ensuring safe recovery transitions and continued medical support at home in Chennai.",
    qualifications: [{ degree: "B.Sc Nursing", institution: "Madras Medical College", year: 2018 }],
    certifications: ["Post-Acute Care Certified", "Wound Care Management", "CPR"],
    workHistory: [{
      organization: "Fortis Malar Hospital Chennai", position: "Home Care Nurse",
      duration: "3 years", startDate: new Date("2019-08-01"), endDate: new Date("2022-08-01"),
    }],
    workingShifts: {
      morning: { available: true, timeRange: "6 AM - 12 PM" },
      afternoon: { available: true, timeRange: "12 PM - 6 PM" },
      evening: { available: true, timeRange: "6 PM - 12 AM" },
      night: { available: false, timeRange: "12 AM - 6 AM" },
    },
    emergencyAvailable: false,
    serviceAreas: ["Velachery", "Tambaram", "Chromepet", "Pallikaranai"],
    ratingBreakdown: { fiveStar: 23, fourStar: 9, threeStar: 3, twoStar: 1, oneStar: 0 },
    performanceMetrics: { successRate: 91, averageResponseTime: "2 hours", casesCompleted: 62, repeatBookings: 20 },
    status: "available",
    topRated: false,
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await Caregiver.deleteMany({});
    await Caregiver.insertMany(caregivers);
    mongoose.connection.close();
  } catch (error) {
    console.error("Error:", error);
    process.exit(1);
  }
};

seedDB();